from django.urls import path

from media.views import (
    add_anime,
    add_cartoon,
    add_movie,
    add_series,
    AnimeListView,
    AnimeCreateView,
    AnimeDetailView,
    AnimeUpdateView,
    AnimeDeleteView,
    CartoonListView,
    CartoonCreateView,
    CartoonDetailView,
    CartoonUpdateView,
    CartoonDeleteView,
    index,
    MovieListView,
    MovieCreateView,
    MovieDetailView,
    MovieUpdateView,
    MovieDeleteView,
    SeriesListView,
    SeriesCreateView,
    SeriesDetailView,
    SeriesUpdateView,
    SeriesDeleteView,
    UserCreateView,
    UserMovieListView,
    UserAnimeListView,
    UserSeriesListView,
    UserCartoonListView,
    update_user_movie_data_view,
    update_user_anime_data_view,
    update_user_series_data_view,
    update_user_cartoon_data_view,
)
