# Generated by Django 5.0.6 on 2024-06-30 12:15

import django.db.models.deletion
import media.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anime",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="cartoon",
            options={"ordering": ("title",)},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="anime",
            name="episodes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="seasons",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="year_released",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cartoon",
            name="episodes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cartoon",
            name="seasons",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cartoon",
            name="year_released",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="year_released",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("seasons", models.IntegerField(null=True)),
                ("episodes", models.IntegerField(null=True)),
                ("year_released", models.IntegerField(null=True)),
                (
                    "genre",
                    models.ManyToManyField(related_name="series", to="media.genre"),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="UserSeriesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.series"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, media.models.UserMediaDataMixin),
        ),
        migrations.AddField(
            model_name="series",
            name="user",
            field=models.ManyToManyField(
                related_name="series",
                through="media.UserSeriesData",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
