# Generated by Django 5.0.6 on 2024-07-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartoon",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="episodes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="seasons",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="series",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
