# Generated by Django 5.0.6 on 2024-06-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_anime_options_alter_cartoon_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anime",
            options={"ordering": ("title",), "verbose_name_plural": "anime"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ("title",), "verbose_name_plural": "series"},
        ),
    ]
