# Generated by Django 5.0.6 on 2024-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_alter_genre_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="episodes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="seasons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="year_released",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartoon",
            name="episodes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartoon",
            name="seasons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartoon",
            name="year_released",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="episodes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="seasons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year_released",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="episodes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="seasons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="year_released",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
