# Generated by Django 5.0.6 on 2024-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_alter_useranimedata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useranimedata",
            options={"ordering": ["-rate"]},
        ),
        migrations.AlterModelOptions(
            name="usercartoondata",
            options={"ordering": ["-rate"]},
        ),
        migrations.AlterModelOptions(
            name="usermoviedata",
            options={"ordering": ["-rate"]},
        ),
        migrations.AlterModelOptions(
            name="userseriesdata",
            options={"ordering": ["-rate"]},
        ),
    ]
